linuxmint/xplayer

- src/xplayer-video-thumbnailer.c
https://github.com/GNOME/totem/commit/1a5f59710f373f48f3a7c70ee4f1a173fbc07040
https://bugzilla.gnome.org/show_bug.cgi?id=742881
> upstream: thumbnailer: Fix missing translation support

- src/backend/bacon-video-widget.c
https://bugzilla.gnome.org/show_bug.cgi?id=728339
> upstream: backend: Reset loaded text subtitles when closing video

- src/xplayer-object.c
Before when trying to scroll seek in music or video files that were shorter in length, the seek would jump too much because the distance was based on constants, with this change it's based on the length of the file.
> Improve scroll seeking in shorter videos/music

- py-compile
Changes the default PYTHON from "python" to "python2". This patch has been in the AUR PKGBUILD for a while for compatibility with arch linux.
> Explicitly use python2 in py-compile

- src/backend/bacon-video-widget.c
Based on https://git.gnome.org/browse/totem/patch/?id=5f274ba9511aee83267ad90ca9b9c9f3db0a84d5
From 5f274ba9511aee83267ad90ca9b9c9f3db0a84d5 Mon Sep 17 00:00:00 2001
From: Bastien Nocera <hadess@hadess.net>
Date: Wed, 6 Mar 2013 22:37:11 +0100
Subject: backend: Remove use of obsolete clutter function
> backend: Remove use of obsolete clutter function

- src/backend/bacon-video-widget.c
- src/backend/xplayer-aspect-frame.c
- src/backend/xplayer-aspect-frame.h
based on https://git.gnome.org/browse/totem/patch/src/backend/bacon-video-widget.c?id=238a61bcf8dbf30d231b6daf445c05399944e472
From 238a61bcf8dbf30d231b6daf445c05399944e472 Mon Sep 17 00:00:00 2001
From: Bastien Nocera <hadess@hadess.net>
Date: Fri, 30 May 2014 16:23:44 +0200
Subject: backend: Automatically rotate mobile phone videos
For certain types of videos, and given a new enough version of
the "qtdemux" plugin, GStreamer will tell us which is the best
rotation for a video. This will automatically show videos the
right way around for videos captured upside-down or in portrait mode
on smartphones.
and
https://github.com/GNOME/totem/commit/a55fedc84a255d742144dabec85e58147bab0edc
From a55fedc84a255d742144dabec85e58147bab0edc Mon Sep 17 00:00:00 2001
From: Bastien Nocera …
> backend: Automatically rotate mobile phone videos

- src/backend/bacon-video-widget.c
based on https://git.gnome.org/browse/totem/patch/src/backend/bacon-video-widget.c?id=e5f01e4bb35a4ad94af5396ab6fcc7129270cb9b
From e5f01e4bb35a4ad94af5396ab6fcc7129270cb9b Mon Sep 17 00:00:00 2001
From: Bastien Nocera <hadess@hadess.net>
Date: Tue, 5 May 2015 18:35:44 +0200
Subject: backend: Don't warn when rotation is unset
But the rotation tag is present. Would throw errors like:
** (totem:3246): WARNING **: Unhandled orientation value: 'rotate-0'
> backend: Don't warn when rotation is unset

- configure.ac
```
configure.ac:624: warning: AC_PROG_CC was called before AX_CHECK_ENABLE_DEBUG
/usr/share/aclocal/ax_check_enable_debug.m4:47: AX_CHECK_ENABLE_DEBUG is expanded from...
/usr/share/aclocal/gnome-common.m4:6: GNOME_DEBUG_CHECK is expanded from...
configure.ac:624: the top level
```
and
```
libgd/Makefile.am:29: warning: source file 'libgd/gd-types-catalog.c' is in a subdirectory,
libgd/Makefile.am:29: but option 'subdir-objects' is disabled
```
> Fix configure.ac warnings

- autogen.sh
```
+ Setting up submodules
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/usr/bin/gnome-autogen.sh
***Warning*** USE_GNOME2_MACROS is deprecated, you may remove it from autogen.sh
***Warning*** PKG_NAME is deprecated, you may remove it from autogen.sh
```
> Fix warnings

- configure.ac
Based on https://git.gnome.org/browse/totem/patch/?id=bfc31c4fca16effd9dda1a191130c80bd86a2117
From bfc31c4fca16effd9dda1a191130c80bd86a2117 Mon Sep 17 00:00:00 2001
From: Bastien Nocera <hadess@hadess.net>
Date: Mon, 27 Apr 2015 13:32:58 +0200
Subject: build: Fix detection of valac
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
AM_PROG_VALAC very helpfully sets $VALAC to:
"Absolute path to the Vala compiler, or simply ‘valac’ if no suitable
compiler Vala could be found at configure runtime."
We were checking for $VALAC being empty, thus still trying to build Vala
plugins even if Vala wasn't available.
> build: Fix detection of valac

- data/org.x.player.gschema.xml.in.in
- data/preferences.ui
- src/xplayer-object.c
- src/xplayer-preferences.c
This will add an option to hide or show subtitles like requested in issue #57 . The default value is false, i.e. no subtitles will be displayed.
> Added option to display or hide subtitles

- src/plugins/screenshot/Makefile.am
- src/plugins/screenshot/xplayer-screenshot-plugin.c
- src/plugins/screenshot/xplayer-screenshot-plugin.h
Fixing:
```
xplayer-screenshot-plugin.c: In function 'make_filename_for_dir':
xplayer-screenshot-plugin.c:420:2: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
filename = g_strdup_printf (_(format), movie_title, i);
^~~~~~~~
xplayer-screenshot-plugin.c:428:3: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
filename = g_strdup_printf (_(format), movie_title, i);
^~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [Makefile:622: libscreenshot_la-xplayer-screenshot-plugin.lo] Error 1
```
Fix borrowed from [Totem](https://github.com/GNOME/totem/commit/c65abe62b4fad9f9eddf2b606eb62a7819c6e091).
> [xplayer-screenshot-plugin] Fix -Werror=format-nonliteral

- debian/control
- src/plugins/dbusservice/dbusservice.plugin.in
- src/plugins/dbusservice/dbusservice.py
- src/plugins/opensubtitles/hash.py
- src/plugins/opensubtitles/opensubtitles.plugin.in
- src/plugins/opensubtitles/opensubtitles.py
- src/plugins/pythonconsole/console.py
- src/plugins/pythonconsole/pythonconsole.plugin.in
- src/plugins/pythonconsole/pythonconsole.py
- src/plugins/xplayer-plugins-engine.c
Fedora has removed the python2 loader from libpeas
Based on
https://github.com/GNOME/totem/commit/e42f0dc5b287e35174158cec5d36332b7a077254
https://github.com/GNOME/totem/commit/53bf51e20899857dede61f538cac71a19e1e4163
https://github.com/GNOME/totem/commit/6022536e085e65c086282c831f27000b13f3abfe
https://github.com/GNOME/totem/commit/687b0a7391765ed7f738b9792afc90b11b9f2dc6
https://github.com/GNOME/totem/commit/3d76122be59abe3db9208fbcfe0123b8b3922bc0
https://github.com/GNOME/totem/commit/d8535bf3544ae0b7dd483bafe190f51eb62a55ab
https://github.com/GNOME/totem/commit/c76e276b415c458e38966d3ec58cd750452c9b15
https://github.com/GNOME/totem/commit/9d6a14fc25515772048ef07a2dc7343241277a43
https://github.com/GNOME/totem/commit/8c8667670f4bf9d4e6714074368e14db79c41b9a …
> Port to python3

- src/plugins/grilo/grilo.ui
- src/plugins/grilo/xplayer-grilo.c
A rather obvious approach – if GtkBuilder cannot get the derived widgets, let's not.
Another way would be to make instances of the needed classes right before initialising GtkBuilder.
> Fix xplayer start-up when compiled with Grilo

- src/plugins/pythonconsole/pythonconsole.py
Based on https://github.com/GNOME/totem/commit/c53f91a3b6458bddc9261077fcf49d46f16fa1a6
The PythonConsole and OutFile classes are exposed publicly by the
console (so that the user can use them dynamically from the console); so
both must be imported from their module first.
https://bugzilla.gnome.org/show_bug.cgi?id=759075
> pythonconsole: Import all classes to expose publicly

- src/gst/xplayer-gst-pixbuf-helpers.c
Based on https://github.com/GNOME/totem/commit/76254280dedb94c3216edd2e7d066c53f6dd90b2
> gst: Fix GstMemory memory leak

- src/plugins/dbusservice/dbusservice.py
Based on https://github.com/GNOME/totem/commit/3f48c7aa83bb26da8f8421209cddfd0be342cb81
https://bugzilla.gnome.org/show_bug.cgi?id=737476
Should fix
```
(cinnamon-screensaver-main.py:1998): GLib-GIO-WARNING **: 21:53:53.913: Received property Position with type i does not match expected type x in the expected interface
(cinnamon:16371): GLib-GIO-WARNING **: 21:53:53.915: Received property Position with type i does not match expected type x in the expected interface
```
> dbusservice: Force Position to be int64

- src/xplayer-video-thumbnailer.c
Based on several commits, I can squash if required.
https://github.com/GNOME/totem/commit/cc43a50c9d0f73654f56a174d17be197e4be01a8
https://github.com/GNOME/totem/commit/28bcfde30b7087c39dba3902885798fbdc888444
https://github.com/GNOME/totem/commit/8d3956f5d53aa03ab1146362fed3eacdc50c531d
https://github.com/GNOME/totem/commit/5f0f049416df05b17926e45b0d54a30dc943588b
https://github.com/GNOME/totem/commit/621a387cbe88c8084796dd601e1efc95b6fd2c00
>  thumbnailer: Add upstream gstreamer blacklist changes

- src/eggsmclient-xsmp.c
Deals with the following warning from #16:
[src/eggsmclient-xsmp.c:1201]: (error) va_list 'ap' was opened but not closed by va_end().
> Deal with a compilation warning (#16)

- src/backend/bacon-video-widget.c
The segfault occurs when bvw->priv->tagcache is NULL and is passed in to gst_tag_list_get_string_index()
As far as I can tell, in all other cases where bvw->priv->tagcache is used, it is either checked for NULL already, or it is passed in to a function that can accept NULLs (g_clear_pointer or gst_tag_list_merge)
> fix segfault in bacon-video-widget.c update_orientation_from_video
